name: release

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Creating .npmrc
        run: |
          cat << EOF > "./.npmrc"
           //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF

      - name: Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
